components:
  schemas:
    ErrorResponse:
      properties:
        error:
          properties:
            message:
              description: A human-readable message describing the error.
              type: string
            type:
              description: The type of error.
              type: string
          type: object
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  description: RESTApi description for a Site site
  title: Site
  version: 1.0.0
openapi: 3.0.0
paths:
  /{PloneSite}/@login:
    parameters:
    - description: Path to the PloneSite
      in: path
      name: PloneSite
      required: true
      schema:
        example: ''
        type: string
    post:
      description: A JWT token can be acquired by posting a user's credentials to
        the @login endpoint
      requestBody:
        content:
          application/json:
            schema:
              properties:
                login:
                  example: admin
                  type: string
                password:
                  example: admin
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  token:
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImZ1bGxuYW1lIjoiIn0.S9kUg8j-Iju0eaOpot7asXiZO8mlJX1fQVt9MPQpXBg
                    type: string
                type: object
          description: User succesfully authenticated
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: User input error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: User input error
        '501':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: User input error
      summary: Login endpoint
servers:
- description: Site API
  url: http://localhost:8080/
  x-healthCheck:
    interval: '300'
    timeout: '15'
    url: https://demo.plone.org
  x-sandbox: false
